openai_api_key = "your key here"

[redis]
host = "localhost"
port = 6379

[langchain]
debug = false

[langsmith]
tracing = true
api_url = "https://api.smith.langchain.com"
api_key = "your key here"
project = "project name"

[ocrspace]
endpoint = "https://api.ocr.space/parse/image"
api_key = "your key here"