default_context:
  project_name: 'termsai'
  project_slug: 'termsai'
  domain_main: 'terms-ai.com'
  domain_staging: 'stag.terms-ai.com'
  docker_swarm_stack_name_main: 'terms-ai-com'
  docker_swarm_stack_name_staging: 'stag-terms-ai-com'
  secret_key: 'pam1249CS1110ragot&'
  first_superuser: 'admin@terms-ai.com'
  first_superuser_password: 'pam1249CS1110ragot&'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.terms-ai.com", "https://stag.terms-ai.com", "https://terms-ai.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@terms-ai.com'
  postgres_password: 'pam1249CS1110ragot&'
  pgadmin_default_user: 'admin@terms-ai.com'
  pgadmin_default_user_password: 'pam1249CS1110ragot&'
  traefik_constraint_tag: 'terms-ai.com'
  traefik_constraint_tag_staging: 'stag.terms-ai.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:pam1249CS1110ragot&'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
